### 7. Repeat problem 6, but use GMM with 3 mixtures instead.

In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.mixture import GaussianMixture

In [2]:
import pandas as pd
data = pd.read_csv('../breast-cancer-wisconsin.data')
data.columns = ['Sample code', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                'Normal Nucleoli', 'Mitoses','Class']
# data = np.array(data)
data

,Sample code,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [3]:
# 取代空值
data = data.replace('?',np.NaN)
data['Bare Nuclei'].unique()
data.shape

(698, 11)

In [4]:
# 用 median() 取代 missing value
data['Bare Nuclei'].fillna(value=int(data['Bare Nuclei'].median()), inplace=True)
data['Bare Nuclei'] = data['Bare Nuclei'].astype("int")

In [5]:
# drop 
data.drop(['Sample code'], axis=1,inplace=True)
data

,Clump Thickness,Uniformity of Cell Size,Uniformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleoli,Mitoses,Class
0,5,4,4,5,7,10,3,2,1,2
1,3,1,1,1,2,2,3,1,1,2
2,6,8,8,1,3,4,3,7,1,2
3,4,1,1,3,2,1,3,1,1,2
4,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...
693,3,1,1,1,3,2,1,1,1,2
694,2,1,1,1,2,1,1,1,1,2
695,5,10,10,3,7,3,8,10,2,4
696,4,8,6,4,3,4,10,6,1,4
697,4,8,8,5,4,5,10,4,1,4

In [6]:
# 抓取資料
df_X = np.array(data.iloc[:,0:9])
df_y = np.array(data.iloc[:,-1])

In [7]:
#Split train and test dataset
X_train, X_test, y_train, y_test = train_test_split(df_X, df_y, test_size=0.3, stratify=df_y)

In [8]:
type(y_train)

numpy.ndarray

In [9]:
# Need to separate training data
ix_2 = (y_train == 2)
train_X2 = X_train[ix_2,:]
ix_4 = (y_train == 4)
train_X4 = X_train[ix_4,:]

In [10]:
# initialize GMM here, you can assign # of mixture here
gmm2 = GaussianMixture(n_components=2)
gmm4 = GaussianMixture(n_components=2)

In [11]:
# Train the model with EM algorithm, one model per class
gmm2.fit(train_X2)
gmm4.fit(train_X4)

GaussianMixture(n_components=2)

In [12]:
# test model
s2 = gmm2.score_samples(X_test)
s4 = gmm4.score_samples(X_test)

In [14]:
s2

array([-1.19179088e+01, -3.88349441e+01,  1.42253053e+01,  1.33559746e+01,
       -1.64185601e+01,  1.40257752e+01,  1.46218447e+01, -4.21709736e+01,
        1.45455929e+01, -4.70958815e+01, -3.26047984e+01, -3.49751376e+01,
       -4.84560645e+01, -3.54709327e+01, -8.61987956e+01, -1.27983103e+01,
       -1.12863284e+01,  1.45455929e+01, -1.74743655e+02, -8.12514630e+01,
       -3.03333499e+01,  1.36892418e+01, -3.93434866e+01,  1.39965499e+01,
        3.14256025e-01,  1.38741913e+01,  1.47760874e+01, -4.80717567e+01,
        1.47760874e+01, -2.04143336e+01,  1.36892418e+01, -6.62252298e+01,
       -1.26722079e+01, -1.14466172e+01, -1.35692464e+01, -4.27065433e+01,
        1.38524676e+01, -2.90112514e+01,  1.36892418e+01,  1.12164685e+01,
        9.78882183e+00,  1.52598002e+01,  1.39965499e+01,  1.11512493e+01,
        1.39965499e+01,  9.57889784e+00, -7.07338332e+01, -3.21422643e+02,
        1.36892418e+01, -1.32993758e+01, -6.99702906e+01, -7.18411944e+02,
       -4.45577612e+01, -7.10814007e+02, -3.21702021e+01,  1.10124451e+00,
       -2.72976537e+01,  1.42253053e+01, -1.11434877e+01, -1.18866932e+01,
        9.57889784e+00, -1.13217012e+01, -1.50454531e+01, -1.31834092e+02,
       -3.04435446e+01, -6.01751347e+01, -1.16078521e+01,  1.48088522e+01,
       -6.51393981e+01,  1.45455929e+01, -4.27324426e+01, -1.28285398e+01,
       -1.23090237e+01, -1.38219069e+01, -1.10643807e+01, -2.80707685e+01,
       -7.64786788e+01,  1.23131187e+01,  1.11512493e+01,  1.28665823e+01,
        6.59608568e+00,  1.44858739e+01,  1.04666267e+01, -1.26715208e+01,
       -1.17571969e+01,  1.52707218e+01,  6.84555180e+00, -1.16236814e+01,
       -1.21309982e+01, -4.50761189e+01,  1.26892508e+01,  1.40257752e+01,
       -1.22947307e+01, -7.04841214e+01, -1.23546917e+01,  1.26892508e+01,
        1.52707218e+01, -2.34682751e+01, -3.48477221e+01, -2.72104010e+01,
        1.42164417e+01,  1.47760874e+01, -1.09955846e+01, -6.59871176e+01,
       -2.20207195e+02,  1.06009393e+01,  1.38524676e+01,  1.24667392e+01,
       -1.32889993e+01,  1.52707218e+01,  1.47760874e+01,  1.26892508e+01,
       -1.12884866e+01, -1.46793387e+01,  1.38524676e+01,  9.40584948e+00,
       -4.20369528e+01, -1.21800167e+01,  1.42164417e+01, -4.15735474e+01,
       -3.32746216e+02, -7.72392107e+02,  1.48088522e+01,  6.17944267e+00,
       -1.21164350e+01, -6.25583587e+01, -1.40938109e+01,  1.47760874e+01,
       -9.44327011e+01,  1.12164685e+01, -2.27439556e+01, -4.57247422e+01,
        1.36892418e+01,  1.48088522e+01,  1.17423338e+01, -1.04374740e+02,
       -4.37439859e+02,  1.46218447e+01,  1.52707218e+01,  1.52707218e+01,
        1.42164417e+01,  1.39965499e+01,  1.48088522e+01, -3.49405484e+01,
       -5.36172926e+01, -1.82312159e+01, -5.50907529e+01, -4.95800409e+01,
        1.18683621e+01, -1.16068983e+01,  1.34446489e+01,  1.52707218e+01,
        1.26142510e+01,  1.18683621e+01, -2.13175899e+01,  1.12164685e+01,
        3.79677809e+00, -2.84032784e+01, -1.12023304e+01,  1.33920112e+01,
       -3.12631072e+01,  6.77766532e+00, -1.40785719e+01, -5.43231939e+01,
       -3.15093186e+01, -5.30391776e+01, -7.07338332e+01, -9.55383022e+01,
        1.30928852e+01,  1.21794104e+01, -2.74835683e+01,  1.21794104e+01,
       -1.40470155e+01, -1.27775852e+01, -1.24874319e+01,  1.38524676e+01,
       -1.57889685e+01, -2.01890134e+01, -3.96360174e+01, -1.73736220e+01,
       -5.03031199e+01,  1.38524676e+01,  1.45455929e+01, -4.90850242e+01,
       -1.08467865e+01,  1.47760874e+01, -9.00748981e+01, -2.18897595e+01,
        1.38524676e+01,  1.46218447e+01, -4.36458972e+02, -3.88795479e+01,
        1.15044142e+01, -1.08936526e+01,  1.36892418e+01, -6.87376188e+02,
       -1.18138620e+01, -3.84075091e+01, -7.66721647e+02, -2.13336779e+01,
        1.82075377e+00, -1.81772553e+01, -4.75709507e+02, -3.91046186e+01,
       -3.50008795e+01, -4.24534335e+01, -1.16833244e+01, -4.13983465e+02,
        1.42164417e+01,  1.52598002e+01])

In [20]:
# Pick the model with Maximum Likelihood
pred2 = np.maximum(s2, s4) #np.logical_and((s2> s4),)
pred4 = np.maximum(s4, s2) #np.logical_and((s4 > s2),)

In [21]:
ans2 = (y_test == 2)
ans4 = (y_test == 4)

In [22]:
acc2 = np.logical_and(pred2, ans2)
acc4 = np.logical_and(pred4, ans4)

In [25]:
acc = sum(acc2) + sum(acc4) 
acc = acc / len(y_test)
acc

1.0

In [24]:
print('Acc = %.2f' % acc)

Acc = 1.00